// One-shot generator: extracts the Unicode identifier range tables from
// upstream/TypeScript/src/compiler/scanner.ts and emits a .inl include.
// Not part of the build; run manually when refreshing upstream tables.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..', '..');
const src = fs.readFileSync(path.join(root, 'upstream', 'TypeScript', 'src', 'compiler', 'scanner.ts'), 'utf8');

function extract(name) {
  const re = new RegExp('const ' + name + ' = \\[([^\\]]+)\\]');
  const m = src.match(re);
  if (!m) throw new Error('missing ' + name);
  return m[1].split(',').map(x => parseInt(x.trim(), 10));
}

const startA = extract('unicodeESNextIdentifierStart');
const partA = extract('unicodeESNextIdentifierPart');
const startB = extract('unicodeES5IdentifierStart');
const partB = extract('unicodeES5IdentifierPart');
console.log('ESNext start:', startA.length, 'part:', partA.length);
console.log('ES5 start:', startB.length, 'part:', partB.length);

function emit(name, arr) {
  const lines = [];
  for (let i = 0; i < arr.length; i += 16) {
    lines.push('    ' + arr.slice(i, i + 16).map(v => String(v)).join(', ') + (i + 16 < arr.length ? ',' : ''));
  }
  return 'static const uint32_t ' + name + '[' + arr.length + '] = {\n' + lines.join('\n') + '\n};\n';
}

let out = '/* Generated by ctsc/src/scanner/_gen_unicode.js - do not edit.\n';
out += ' * Source: upstream/TypeScript/src/compiler/scanner.ts\n';
out += ' * unicodeESNextIdentifierStart / unicodeESNextIdentifierPart / unicodeES5IdentifierStart / unicodeES5IdentifierPart.\n';
out += ' * Tables are sorted ascending [lo, hi] range pairs (inclusive) covering non-ASCII code points only.\n';
out += ' */\n\n';
out += emit('unicode_esnext_id_start', startA);
out += '\n';
out += emit('unicode_esnext_id_part', partA);
out += '\n';
out += emit('unicode_es5_id_start', startB);
out += '\n';
out += emit('unicode_es5_id_part', partB);

fs.writeFileSync(path.join(__dirname, 'unicode_id_tables.inl'), out);
console.log('wrote ctsc/src/scanner/unicode_id_tables.inl');
