#include "ctsc/scanner.h"

#include <string.h>

/*
 * Must stay in 1:1 correspondence with CtscSyntaxKind.
 * Names are verbatim ts.SyntaxKind member names so the JSON oracle matches.
 * When the agent adds new kinds, append both the enum and the name.
 */
static const char* const k_names[CTSC_SK__COUNT] = {
    [CTSC_SK_Unknown]                           = "Unknown",
    [CTSC_SK_EndOfFileToken]                    = "EndOfFileToken",
    [CTSC_SK_SingleLineCommentTrivia]           = "SingleLineCommentTrivia",
    [CTSC_SK_MultiLineCommentTrivia]            = "MultiLineCommentTrivia",
    [CTSC_SK_NewLineTrivia]                     = "NewLineTrivia",
    [CTSC_SK_WhitespaceTrivia]                  = "WhitespaceTrivia",

    [CTSC_SK_NumericLiteral]                    = "NumericLiteral",
    [CTSC_SK_BigIntLiteral]                     = "BigIntLiteral",
    [CTSC_SK_StringLiteral]                     = "StringLiteral",
    [CTSC_SK_RegularExpressionLiteral]          = "RegularExpressionLiteral",
    [CTSC_SK_NoSubstitutionTemplateLiteral]     = "NoSubstitutionTemplateLiteral",
    [CTSC_SK_TemplateHead]                      = "TemplateHead",
    [CTSC_SK_TemplateMiddle]                    = "TemplateMiddle",
    [CTSC_SK_TemplateTail]                      = "TemplateTail",

    [CTSC_SK_OpenBraceToken]                    = "OpenBraceToken",
    [CTSC_SK_CloseBraceToken]                   = "CloseBraceToken",
    [CTSC_SK_OpenParenToken]                    = "OpenParenToken",
    [CTSC_SK_CloseParenToken]                   = "CloseParenToken",
    [CTSC_SK_OpenBracketToken]                  = "OpenBracketToken",
    [CTSC_SK_CloseBracketToken]                 = "CloseBracketToken",
    [CTSC_SK_DotToken]                          = "DotToken",
    [CTSC_SK_DotDotDotToken]                    = "DotDotDotToken",
    [CTSC_SK_SemicolonToken]                    = "SemicolonToken",
    [CTSC_SK_CommaToken]                        = "CommaToken",
    [CTSC_SK_QuestionDotToken]                  = "QuestionDotToken",
    [CTSC_SK_LessThanToken]                     = "LessThanToken",
    [CTSC_SK_LessThanSlashToken]                = "LessThanSlashToken",
    [CTSC_SK_GreaterThanToken]                  = "GreaterThanToken",
    [CTSC_SK_LessThanEqualsToken]               = "LessThanEqualsToken",
    [CTSC_SK_GreaterThanEqualsToken]            = "GreaterThanEqualsToken",
    [CTSC_SK_EqualsEqualsToken]                 = "EqualsEqualsToken",
    [CTSC_SK_ExclamationEqualsToken]            = "ExclamationEqualsToken",
    [CTSC_SK_EqualsEqualsEqualsToken]           = "EqualsEqualsEqualsToken",
    [CTSC_SK_ExclamationEqualsEqualsToken]      = "ExclamationEqualsEqualsToken",
    [CTSC_SK_EqualsGreaterThanToken]            = "EqualsGreaterThanToken",
    [CTSC_SK_PlusToken]                         = "PlusToken",
    [CTSC_SK_MinusToken]                        = "MinusToken",
    [CTSC_SK_AsteriskToken]                     = "AsteriskToken",
    [CTSC_SK_AsteriskAsteriskToken]             = "AsteriskAsteriskToken",
    [CTSC_SK_SlashToken]                        = "SlashToken",
    [CTSC_SK_PercentToken]                      = "PercentToken",
    [CTSC_SK_PlusPlusToken]                     = "PlusPlusToken",
    [CTSC_SK_MinusMinusToken]                   = "MinusMinusToken",
    [CTSC_SK_LessThanLessThanToken]             = "LessThanLessThanToken",
    [CTSC_SK_GreaterThanGreaterThanToken]       = "GreaterThanGreaterThanToken",
    [CTSC_SK_GreaterThanGreaterThanGreaterThanToken] = "GreaterThanGreaterThanGreaterThanToken",
    [CTSC_SK_AmpersandToken]                    = "AmpersandToken",
    [CTSC_SK_BarToken]                          = "BarToken",
    [CTSC_SK_CaretToken]                        = "CaretToken",
    [CTSC_SK_ExclamationToken]                  = "ExclamationToken",
    [CTSC_SK_TildeToken]                        = "TildeToken",
    [CTSC_SK_AmpersandAmpersandToken]           = "AmpersandAmpersandToken",
    [CTSC_SK_BarBarToken]                       = "BarBarToken",
    [CTSC_SK_QuestionToken]                     = "QuestionToken",
    [CTSC_SK_ColonToken]                        = "ColonToken",
    [CTSC_SK_AtToken]                           = "AtToken",
    [CTSC_SK_QuestionQuestionToken]             = "QuestionQuestionToken",
    [CTSC_SK_EqualsToken]                       = "EqualsToken",
    [CTSC_SK_PlusEqualsToken]                   = "PlusEqualsToken",
    [CTSC_SK_MinusEqualsToken]                  = "MinusEqualsToken",
    [CTSC_SK_AsteriskEqualsToken]               = "AsteriskEqualsToken",
    [CTSC_SK_SlashEqualsToken]                  = "SlashEqualsToken",
    [CTSC_SK_PercentEqualsToken]                = "PercentEqualsToken",
    [CTSC_SK_GreaterThanGreaterThanEqualsToken] = "GreaterThanGreaterThanEqualsToken",
    [CTSC_SK_GreaterThanGreaterThanGreaterThanEqualsToken] = "GreaterThanGreaterThanGreaterThanEqualsToken",

    [CTSC_SK_Identifier]                        = "Identifier",
    [CTSC_SK_PrivateIdentifier]                 = "PrivateIdentifier",

    [CTSC_SK_BreakKeyword]                      = "BreakKeyword",
    [CTSC_SK_CaseKeyword]                       = "CaseKeyword",
    [CTSC_SK_CatchKeyword]                      = "CatchKeyword",
    [CTSC_SK_ClassKeyword]                      = "ClassKeyword",
    [CTSC_SK_ConstKeyword]                      = "ConstKeyword",
    [CTSC_SK_ContinueKeyword]                   = "ContinueKeyword",
    [CTSC_SK_DebuggerKeyword]                   = "DebuggerKeyword",
    [CTSC_SK_DefaultKeyword]                    = "DefaultKeyword",
    [CTSC_SK_DeleteKeyword]                     = "DeleteKeyword",
    [CTSC_SK_DoKeyword]                         = "DoKeyword",
    [CTSC_SK_ElseKeyword]                       = "ElseKeyword",
    [CTSC_SK_EnumKeyword]                       = "EnumKeyword",
    [CTSC_SK_ExportKeyword]                     = "ExportKeyword",
    [CTSC_SK_ExtendsKeyword]                    = "ExtendsKeyword",
    [CTSC_SK_FalseKeyword]                      = "FalseKeyword",
    [CTSC_SK_FinallyKeyword]                    = "FinallyKeyword",
    [CTSC_SK_ForKeyword]                        = "ForKeyword",
    [CTSC_SK_FunctionKeyword]                   = "FunctionKeyword",
    [CTSC_SK_IfKeyword]                         = "IfKeyword",
    [CTSC_SK_ImportKeyword]                     = "ImportKeyword",
    [CTSC_SK_InKeyword]                         = "InKeyword",
    [CTSC_SK_InstanceOfKeyword]                 = "InstanceOfKeyword",
    [CTSC_SK_NewKeyword]                        = "NewKeyword",
    [CTSC_SK_NullKeyword]                       = "NullKeyword",
    [CTSC_SK_ReturnKeyword]                     = "ReturnKeyword",
    [CTSC_SK_SuperKeyword]                      = "SuperKeyword",
    [CTSC_SK_SwitchKeyword]                     = "SwitchKeyword",
    [CTSC_SK_ThisKeyword]                       = "ThisKeyword",
    [CTSC_SK_ThrowKeyword]                      = "ThrowKeyword",
    [CTSC_SK_TrueKeyword]                       = "TrueKeyword",
    [CTSC_SK_TryKeyword]                        = "TryKeyword",
    [CTSC_SK_TypeOfKeyword]                     = "TypeOfKeyword",
    [CTSC_SK_VarKeyword]                        = "VarKeyword",
    [CTSC_SK_VoidKeyword]                       = "VoidKeyword",
    [CTSC_SK_WhileKeyword]                      = "WhileKeyword",
    [CTSC_SK_WithKeyword]                       = "WithKeyword",

    [CTSC_SK_AsKeyword]                         = "AsKeyword",
    [CTSC_SK_AsyncKeyword]                      = "AsyncKeyword",
    [CTSC_SK_AwaitKeyword]                      = "AwaitKeyword",
    [CTSC_SK_ConstructorKeyword]                = "ConstructorKeyword",
    [CTSC_SK_FromKeyword]                       = "FromKeyword",
    [CTSC_SK_GetKeyword]                        = "GetKeyword",
    [CTSC_SK_LetKeyword]                        = "LetKeyword",
    [CTSC_SK_OfKeyword]                         = "OfKeyword",
    [CTSC_SK_SetKeyword]                        = "SetKeyword",
    [CTSC_SK_YieldKeyword]                      = "YieldKeyword",

    [CTSC_SK_AbstractKeyword]                   = "AbstractKeyword",
    [CTSC_SK_AnyKeyword]                        = "AnyKeyword",
    [CTSC_SK_BooleanKeyword]                    = "BooleanKeyword",
    [CTSC_SK_DeclareKeyword]                    = "DeclareKeyword",
    [CTSC_SK_InterfaceKeyword]                  = "InterfaceKeyword",
    [CTSC_SK_ImplementsKeyword]                 = "ImplementsKeyword",
    [CTSC_SK_ModuleKeyword]                     = "ModuleKeyword",
    [CTSC_SK_NamespaceKeyword]                  = "NamespaceKeyword",
    [CTSC_SK_NumberKeyword]                     = "NumberKeyword",
    [CTSC_SK_ObjectKeyword]                     = "ObjectKeyword",
    [CTSC_SK_PrivateKeyword]                    = "PrivateKeyword",
    [CTSC_SK_ProtectedKeyword]                  = "ProtectedKeyword",
    [CTSC_SK_PublicKeyword]                     = "PublicKeyword",
    [CTSC_SK_ReadonlyKeyword]                   = "ReadonlyKeyword",
    [CTSC_SK_StaticKeyword]                     = "StaticKeyword",
    [CTSC_SK_StringKeyword]                     = "StringKeyword",
    [CTSC_SK_SymbolKeyword]                     = "SymbolKeyword",
    [CTSC_SK_TypeKeyword]                       = "TypeKeyword",
    [CTSC_SK_UndefinedKeyword]                  = "UndefinedKeyword",
    [CTSC_SK_NeverKeyword]                      = "NeverKeyword",
    [CTSC_SK_UnknownKeyword]                    = "UnknownKeyword",

    [CTSC_SK_SourceFile]                        = "SourceFile",
    [CTSC_SK_Block]                             = "Block",
    [CTSC_SK_VariableStatement]                 = "VariableStatement",
    [CTSC_SK_VariableDeclarationList]           = "VariableDeclarationList",
    [CTSC_SK_VariableDeclaration]               = "VariableDeclaration",
    [CTSC_SK_ExpressionStatement]               = "ExpressionStatement",
    [CTSC_SK_EmptyStatement]                    = "EmptyStatement",
    [CTSC_SK_IfStatement]                       = "IfStatement",
    [CTSC_SK_WhileStatement]                    = "WhileStatement",
    [CTSC_SK_ForStatement]                      = "ForStatement",
    [CTSC_SK_ForInStatement]                    = "ForInStatement",
    [CTSC_SK_ForOfStatement]                    = "ForOfStatement",
    [CTSC_SK_DoStatement]                       = "DoStatement",
    [CTSC_SK_BreakStatement]                    = "BreakStatement",
    [CTSC_SK_ContinueStatement]                 = "ContinueStatement",
    [CTSC_SK_DebuggerStatement]                 = "DebuggerStatement",
    [CTSC_SK_TryStatement]                      = "TryStatement",
    [CTSC_SK_WithStatement]                     = "WithStatement",
    [CTSC_SK_SwitchStatement]                 = "SwitchStatement",
    [CTSC_SK_CaseBlock]                         = "CaseBlock",
    [CTSC_SK_CaseClause]                        = "CaseClause",
    [CTSC_SK_DefaultClause]                     = "DefaultClause",
    [CTSC_SK_ParenthesizedExpression]           = "ParenthesizedExpression",
    [CTSC_SK_ConditionalExpression]             = "ConditionalExpression",
    [CTSC_SK_ReturnStatement]                   = "ReturnStatement",
    [CTSC_SK_ThrowStatement]                    = "ThrowStatement",
    [CTSC_SK_FunctionDeclaration]               = "FunctionDeclaration",
    [CTSC_SK_FunctionExpression]                = "FunctionExpression",
    [CTSC_SK_Parameter]                         = "Parameter",
    [CTSC_SK_BinaryExpression]                  = "BinaryExpression",
    [CTSC_SK_PrefixUnaryExpression]             = "PrefixUnaryExpression",
    [CTSC_SK_PostfixUnaryExpression]            = "PostfixUnaryExpression",
    [CTSC_SK_CallExpression]                    = "CallExpression",
    [CTSC_SK_NewExpression]                     = "NewExpression",
    [CTSC_SK_PropertyAccessExpression]          = "PropertyAccessExpression",
    [CTSC_SK_ElementAccessExpression]           = "ElementAccessExpression",
    [CTSC_SK_ArrayLiteralExpression]            = "ArrayLiteralExpression",
    [CTSC_SK_ObjectLiteralExpression]           = "ObjectLiteralExpression",
    [CTSC_SK_PropertyAssignment]                = "PropertyAssignment",
    [CTSC_SK_ShorthandPropertyAssignment]       = "ShorthandPropertyAssignment",
    [CTSC_SK_ComputedPropertyName]              = "ComputedPropertyName",
    [CTSC_SK_MethodDeclaration]                 = "MethodDeclaration",
    [CTSC_SK_GetAccessor]                       = "GetAccessor",
    [CTSC_SK_SetAccessor]                       = "SetAccessor",
    [CTSC_SK_PropertyDeclaration]               = "PropertyDeclaration",
    [CTSC_SK_SemicolonClassElement]             = "SemicolonClassElement",
    [CTSC_SK_ClassDeclaration]                  = "ClassDeclaration",
    [CTSC_SK_ClassExpression]                   = "ClassExpression",
    [CTSC_SK_InterfaceDeclaration]              = "InterfaceDeclaration",
    [CTSC_SK_TypeAliasDeclaration]              = "TypeAliasDeclaration",
    [CTSC_SK_HeritageClause]                    = "HeritageClause",
    [CTSC_SK_ExpressionWithTypeArguments]       = "ExpressionWithTypeArguments",
    [CTSC_SK_EnumDeclaration]                   = "EnumDeclaration",
    [CTSC_SK_EnumMember]                        = "EnumMember",
    [CTSC_SK_ArrowFunction]                     = "ArrowFunction",
    [CTSC_SK_TypeReference]                     = "TypeReference",
    [CTSC_SK_TypeLiteral]                       = "TypeLiteral",
    [CTSC_SK_TypeParameter]                     = "TypeParameter",
    [CTSC_SK_PropertySignature]                 = "PropertySignature",
    [CTSC_SK_VoidExpression]                    = "VoidExpression",
    [CTSC_SK_DeleteExpression]                  = "DeleteExpression",
    [CTSC_SK_TypeOfExpression]                  = "TypeOfExpression",
    [CTSC_SK_YieldExpression]                   = "YieldExpression",
    [CTSC_SK_OmittedExpression]                 = "OmittedExpression",
    [CTSC_SK_ObjectBindingPattern]              = "ObjectBindingPattern",
    [CTSC_SK_ArrayBindingPattern]               = "ArrayBindingPattern",
    [CTSC_SK_BindingElement]                    = "BindingElement",
    [CTSC_SK_TemplateExpression]                = "TemplateExpression",
    [CTSC_SK_TemplateSpan]                      = "TemplateSpan",
    [CTSC_SK_TaggedTemplateExpression]          = "TaggedTemplateExpression",
    [CTSC_SK_ModuleDeclaration]                 = "ModuleDeclaration",
    [CTSC_SK_ModuleBlock]                       = "ModuleBlock",
    [CTSC_SK_TypeAssertionExpression]           = "TypeAssertionExpression",
    [CTSC_SK_AsExpression]                      = "AsExpression",
    [CTSC_SK_AwaitExpression]                   = "AwaitExpression",
    [CTSC_SK_SpreadAssignment]                  = "SpreadAssignment",
    [CTSC_SK_SpreadElement]                     = "SpreadElement",
    [CTSC_SK_ImportDeclaration]                 = "ImportDeclaration",
    [CTSC_SK_ImportClause]                      = "ImportClause",
    [CTSC_SK_NamedImports]                      = "NamedImports",
    [CTSC_SK_NamespaceImport]                 = "NamespaceImport",
    [CTSC_SK_ImportSpecifier]                   = "ImportSpecifier",
    [CTSC_SK_ExportDeclaration]                 = "ExportDeclaration",
    [CTSC_SK_NamedExports]                      = "NamedExports",
    [CTSC_SK_ExportSpecifier]                   = "ExportSpecifier",
    [CTSC_SK_NamespaceExport]                   = "NamespaceExport",
    [CTSC_SK_CatchClause]                       = "CatchClause",
    [CTSC_SK_LabeledStatement]                  = "LabeledStatement",
    [CTSC_SK_TypeQuery]                         = "TypeQuery",
};

const char* ctsc_syntax_kind_name(CtscSyntaxKind k) {
    if ((unsigned)k >= (unsigned)CTSC_SK__COUNT) { return "Unknown"; }
    const char* n = k_names[k];
    return n ? n : "Unknown";
}

typedef struct {
    const char*    name;
    size_t         len;
    CtscSyntaxKind kind;
} Keyword;

static const Keyword k_keywords[] = {
    { "abstract",   8, CTSC_SK_AbstractKeyword },
    { "any",        3, CTSC_SK_AnyKeyword },
    { "as",         2, CTSC_SK_AsKeyword },
    { "async",      5, CTSC_SK_AsyncKeyword },
    { "await",      5, CTSC_SK_AwaitKeyword },
    { "boolean",    7, CTSC_SK_BooleanKeyword },
    { "break",      5, CTSC_SK_BreakKeyword },
    { "case",       4, CTSC_SK_CaseKeyword },
    { "catch",      5, CTSC_SK_CatchKeyword },
    { "class",      5, CTSC_SK_ClassKeyword },
    { "const",      5, CTSC_SK_ConstKeyword },
    { "constructor", 11, CTSC_SK_ConstructorKeyword },
    { "continue",   8, CTSC_SK_ContinueKeyword },
    { "debugger",   8, CTSC_SK_DebuggerKeyword },
    { "declare",    7, CTSC_SK_DeclareKeyword },
    { "default",    7, CTSC_SK_DefaultKeyword },
    { "delete",     6, CTSC_SK_DeleteKeyword },
    { "do",         2, CTSC_SK_DoKeyword },
    { "else",       4, CTSC_SK_ElseKeyword },
    { "enum",       4, CTSC_SK_EnumKeyword },
    { "export",     6, CTSC_SK_ExportKeyword },
    { "extends",    7, CTSC_SK_ExtendsKeyword },
    { "false",      5, CTSC_SK_FalseKeyword },
    { "finally",    7, CTSC_SK_FinallyKeyword },
    { "for",        3, CTSC_SK_ForKeyword },
    { "from",       4, CTSC_SK_FromKeyword },
    { "function",   8, CTSC_SK_FunctionKeyword },
    { "get",        3, CTSC_SK_GetKeyword },
    { "if",         2, CTSC_SK_IfKeyword },
    { "implements", 10, CTSC_SK_ImplementsKeyword },
    { "import",     6, CTSC_SK_ImportKeyword },
    { "in",         2, CTSC_SK_InKeyword },
    { "instanceof", 10, CTSC_SK_InstanceOfKeyword },
    { "interface",  9, CTSC_SK_InterfaceKeyword },
    { "let",        3, CTSC_SK_LetKeyword },
    { "module",     6, CTSC_SK_ModuleKeyword },
    { "namespace",  9, CTSC_SK_NamespaceKeyword },
    { "new",        3, CTSC_SK_NewKeyword },
    { "null",       4, CTSC_SK_NullKeyword },
    { "number",     6, CTSC_SK_NumberKeyword },
    { "object",     6, CTSC_SK_ObjectKeyword },
    { "of",         2, CTSC_SK_OfKeyword },
    { "private",    7, CTSC_SK_PrivateKeyword },
    { "protected",  9, CTSC_SK_ProtectedKeyword },
    { "public",     6, CTSC_SK_PublicKeyword },
    { "readonly",   8, CTSC_SK_ReadonlyKeyword },
    { "return",     6, CTSC_SK_ReturnKeyword },
    { "set",        3, CTSC_SK_SetKeyword },
    { "static",     6, CTSC_SK_StaticKeyword },
    { "string",     6, CTSC_SK_StringKeyword },
    { "super",      5, CTSC_SK_SuperKeyword },
    { "switch",     6, CTSC_SK_SwitchKeyword },
    { "symbol",     6, CTSC_SK_SymbolKeyword },
    { "this",       4, CTSC_SK_ThisKeyword },
    { "throw",      5, CTSC_SK_ThrowKeyword },
    { "true",       4, CTSC_SK_TrueKeyword },
    { "try",        3, CTSC_SK_TryKeyword },
    { "type",       4, CTSC_SK_TypeKeyword },
    { "typeof",     6, CTSC_SK_TypeOfKeyword },
    { "undefined",  9, CTSC_SK_UndefinedKeyword },
    { "never",      5, CTSC_SK_NeverKeyword },
    { "unknown",    7, CTSC_SK_UnknownKeyword },
    { "var",        3, CTSC_SK_VarKeyword },
    { "void",       4, CTSC_SK_VoidKeyword },
    { "while",      5, CTSC_SK_WhileKeyword },
    { "with",       4, CTSC_SK_WithKeyword },
    { "yield",      5, CTSC_SK_YieldKeyword },
};

CtscSyntaxKind ctsc_identifier_or_keyword(const uint16_t* text, size_t len) {
    if (len == 0 || len > 16) { return CTSC_SK_Identifier; }
    for (size_t i = 0; i < sizeof(k_keywords) / sizeof(k_keywords[0]); ++i) {
        const Keyword* k = &k_keywords[i];
        if (k->len != len) { continue; }
        bool match = true;
        for (size_t j = 0; j < len; ++j) {
            if ((uint16_t)k->name[j] != text[j]) { match = false; break; }
        }
        if (match) { return k->kind; }
    }
    return CTSC_SK_Identifier;
}
